[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 15.0

[font.bold]
family = "Hack Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.85
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [{key="Q", mods="Command", action="None"}]
